### ISSUE TITLE
Ubuntu does not have /etc/sysconfig dir which fails Chef run

### ISSUE THREAD

**Issue by rmldsky** [sous-chefs/varnish#159] opened 2018-04-04 09:21 UTC
### Cookbook version
3.4

### Chef-client version
12.15.19

### Platform Details
Ubuntu 14.04

### Scenario:
I only run this recipe in my `kitchen` (`recipe[varnish4]`)
```
include_recipe 'apt'
include_recipe 'varnish'

varnish_repo 'configure' do
  major_version 4.1
end

package 'varnish'
package 'varnish-dev'

service 'varnish' do
  action [:enable, :start]
end

varnish_log 'default_ncsa' do
  log_format 'varnishncsa'
end
```

### Steps to Reproduce:
`.kitchen.yml`
```
---
driver:
  name: docker
  use_sudo: false
  privileged: true
  use_internal_docker_network: true
  provision_command: 
    - (echo "version=12.15.19"; curl -L https://www.opscode.com/chef/install.sh) | sudo bash
    - apt-get update
    - apt-get install -y python-software-properties
    - useradd -m ubuntu -s /bin/bash
  require_chef_omnibus: false

provisioner: 
  name: chef_solo
  chef_omnibus_root: /opt/chef

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[varnish4]
    attributes: {
      "ec2": { "hostname": "localhost" },
    }
```

### Expected Result:
Chef client success.

### Actual Result:
```
           * link[/etc/sysconfig/varnishncsa] action create (skipped due to only_if)
           * template[init_varnishncsa] action create
             * Parent directory /etc/sysconfig does not exist.
             ================================================================================
             Error executing action `create` on resource 'template[init_varnishncsa]'
             ================================================================================

             Chef::Exceptions::EnclosingDirectoryDoesNotExist
             ------------------------------------------------
             Parent directory /etc/sysconfig does not exist.

             Cookbook Trace:
             ---------------
             /tmp/kitchen/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:78:in `run_action'
             /tmp/kitchen/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `block (2 levels) in converge'
             /tmp/kitchen/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `each'
             /tmp/kitchen/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `block in converge'
             /tmp/kitchen/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:105:in `converge'
             /tmp/kitchen/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:78:in `run_action'
             /tmp/kitchen/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `block (2 levels) in converge'
             /tmp/kitchen/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `each'
             /tmp/kitchen/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `block in converge'
             /tmp/kitchen/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:105:in `converge'

             Resource Declaration:
             ---------------------
             # In /tmp/kitchen/cache/cookbooks/varnish/resources/varnish_log.rb

       53:   template "init_#{new_resource.log_format}" do
       54:     path template_path(new_resource.log_format)
       55:     source template_source
       56:     cookbook 'varnish'
       57:     owner 'root'
       58:     group 'root'
       59:     mode '0644'
       60:     variables(
       61:       config: new_resource
       62:     )
       63:     action :create
       64:     notifies :restart, "service[#{new_resource.log_format}]", :delayed
       65:     notifies :run, 'execute[systemctl-daemon-reload]', :immediately if node['init_package'] == 'systemd'
       66:   end
       67:

             Compiled Resource:
             ------------------
             # Declared in /tmp/kitchen/cache/cookbooks/varnish/resources/varnish_log.rb:53:in `block in class_from_file'

             template("init_varnishncsa") do
        action [:create]
        retries 0
        retry_delay 2
        default_guard_interpreter :default
        source "varnishlog.erb"
        cookbook "varnish"
        variables {:config=><varnish_varnish_log[default_ncsa] @name: "default_ncsa" @noop: nil @before: nil @params: {} @provider: nil @allowed_actions: [:nothing, :configure] @action: [:configure] @updated: false @updated_by_last_action: false @supports: {} @ignore_failure: false @retries: 0 @retry_delay: 2 @source_line: "/tmp/kitchen/cache/cookbooks/socialguide/recipes/varnish4.rb:15:in `from_file'" @guard_interpreter: nil @default_guard_interpreter: :default @elapsed_time: 0 @sensitive: false @declared_type: :varnish_log @cookbook_name: "socialguide" @recipe_name: "varnish4" @log_format: "varnishncsa" @logrotate_path: "/etc/logrotate.d">}
        declared_type :template
        cookbook_name "socialguide"
        owner "root"
        group "root"
        mode "0644"
        path "/etc/sysconfig/varnishncsa"
             end

             Platform:
             ---------
             x86_64-linux


           ================================================================================
           Error executing action `configure` on resource 'varnish_varnish_log[default_ncsa]'
           ================================================================================

           Chef::Exceptions::EnclosingDirectoryDoesNotExist
           ------------------------------------------------
           template[init_varnishncsa] (/tmp/kitchen/cache/cookbooks/varnish/resources/varnish_log.rb line 53) had an error: Chef::Exceptions::EnclosingDirectoryDoesNotExist: Parent directory /etc/sysconfig does not exist.

           Cookbook Trace:
           ---------------
           /tmp/kitchen/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:78:in `run_action'
           /tmp/kitchen/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `block (2 levels) in converge'
           /tmp/kitchen/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `each'
           /tmp/kitchen/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `block in converge'
           /tmp/kitchen/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:105:in `converge'
           /tmp/kitchen/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:78:in `run_action'
           /tmp/kitchen/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `block (2 levels) in converge'
           /tmp/kitchen/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `each'
           /tmp/kitchen/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `block in converge'
           /tmp/kitchen/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:105:in `converge'

           Resource Declaration:
           ---------------------
           # In /tmp/kitchen/cache/cookbooks/socialguide/recipes/varnish4.rb

            15: varnish_log 'default_ncsa' do
            16:   log_format 'varnishncsa'
            17: end

           Compiled Resource:
           ------------------
           # Declared in /tmp/kitchen/cache/cookbooks/socialguide/recipes/varnish4.rb:15:in `from_file'

           varnish_varnish_log("default_ncsa") do
             action [:configure]
             updated true
             updated_by_last_action true
             retries 0
             retry_delay 2
             default_guard_interpreter :default
             declared_type :varnish_log
             cookbook_name "socialguide"
             recipe_name "varnish4"
             log_format "varnishncsa"
             logrotate_path "/etc/logrotate.d"
           end

           Platform:
           ---------
           x86_64-linux
```

**Comment by rmldsky** [comment] 2018-04-04 09:47
Sorry it seems in `kitchen` `node[init_package]` is neither set to `sshd` :(

```
chef (12.15.19)> node['init_package']
 => "sshd"
```

Need to find other way around this :/

**Comment by RyanJarv** [comment] 2018-04-04 21:49
Kitchen should be working ok, we use it to run the integration tests. Do you know what might be setting it to sshd?

If it's not a bug I would be curious what that means. Also just a thought might make sense for us to fail with a message on unknown init systems here: https://github.com/sous-chefs/varnish/blob/3e9c28e8c181f3a2bab50a711be5f3af584322b9/resources/log.rb#L86

**Comment by rmldsky** [comment] 2018-04-05 14:24
Thanks for getting back on this. I'm clueless why in kitchen it is set to `sshd`, maybe its `kitchen-docker` driver, I'll try to debug further, but for now just dropped the `varnish_log` resource from the recipe to test rest of the stuff I have there.

And yes, the message of some sort for the non-supported `init` would be more helpful :)

**Comment by rmldsky** [comment] 2018-06-26 11:21
Just FYI I have used `kitchen-dokken` (varnish cookbook `3.5`, chef `12.19.36`) and redo slightly my `kitchen.yml` and it worked. I guess it was `kitchen-docker` doing some stuff under the hood. You can close this issue or keep it as a reminder to update the `non-supported init` msg.

Thanks!

**Comment by damacus** [comment] 2018-06-26 12:47
Closing as resolved. 

Thanks everyone for debugging this issue!

**Closed by damacus** 2018-06-26 12:47 UTC
