### ISSUE TITLE
The log format in the ncsa log is not taking from ncsa_format_string

### ISSUE THREAD

**Issue by dilipsonu** [sous-chefs/varnish#125] opened 2017-03-16 23:06 UTC
### Cookbook version
2.5

### Chef-client version
12.4.1

### Platform Details
```
-bash-4.1$ uname -a
Linux XXXXXXXX 2.6.32-431.el6.x86_64 #1 SMP Sun Nov 10 22:19:54 EST 2013 x86_64 x86_64 x86_64 GNU/Linux
-bash-4.1$
```

### Scenario:
I am trying to print the log with hit and miss using varnishncsa log

### recipe 
```
varnish_log 'default_ncsa' do
  file_name node['varnish']['ncsa']['file_name']
  pid node['varnish']['ncsa']['pid']
  log_format node['varnish']['ncsa']['log_format']
  ncsa_format_string '%h|%l|%u|%t|\"%r\"|%s|%b|\"%{Referer}i\"|\"%{Varnish:hitmiss}x\"|\"%{User-agent}i\"'
  logrotate node['varnish']['ncsa']['logrotate']
  logrotate_path node['varnish']['ncsa']['logrotate_path']
	action [:configure]
end
```

 ### VarnishNCSA Logging Settings
```
default['varnish']['ncsa']['file_name'] = '/var/log/varnish/varnishncsa.log'
default['varnish']['ncsa']['pid'] = '/var/run/varnishncsa.pid'
default['varnish']['ncsa']['log_format'] = 'varnishncsa'
default['varnish']['ncsa']['logrotate'] = true
default['varnish']['ncsa']['logrotate_path'] = '/etc/logrotate.d'
```

### Auto generated DAEMON_OPTS options

```
bash-4.1$ pwd
/etc/default
-bash-4.1$ cat varnishncsa
# Configuration file for varnishncsa
#
# /etc/init.d/varnishlog variable $DAEMON_OPTS will be overridden
# by the variable which will be set from this shell script fragment.
#

# Overriding the logfile and pidfile variables
VARNISHNCSA_ENABLED=1
LOGFILE=/var/log/varnish/varnishncsa.log
PIDFILE=/var/run/varnishncsa.pid
LOG_FORMAT="%h|%l|%u|%t|\"%r\"|%s|%b|\"%{Referer}i\"|\"%{Varnish:hitmiss}x\"|\"%{User-agent}i\""

# Default varnish instance name is the local nodename.  Can be overridden with
# the -n switch, to have more instances on a single server.
INSTANCE=varnish-xxxxx-development
# Override the Daemon options
DAEMON_OPTS="-a -w $LOGFILE -D -P $PIDFILE \
	     -F '${LOG_FORMAT}' \
          "
-bash-4.1$
```

### Expected Result:
Along with the log it should print the hit and miss also like below
`10.48.XXX.XX|-|-|[16/Mar/2017:18:45:21 -0400]|"GET http://host/product/_manage/health HTTP/1.1"|200|6506|"-"|"hit"|"PostmanRuntime/3.0.11-hotfix.2"`

### Actual Result:
I am getting the log in below format

`10.2.XX.XX - - [16/Mar/2017:15:58:19 -0700] "GET http://hostname/product/_manage/health HTTP/1.0" 200 272 "-" "-"`

**Comment by RyanJarv** [comment] 2017-03-21 02:56
Was able to reproduce this on CentOS, looks like varnishncsa resource is writing the defaults file to /etc/default/varnishncsa and the init script expects it to be at /etc/sysconfig/varnishncsa.

Thanks for the report, we'll look into getting this fixed.

**Comment by dilipsonu** [comment] 2017-03-21 03:26
Thanks, in my case to achieve my requirements i overwrote the varnishncsa file using template

**Comment by rshade** [comment] 2017-03-21 13:13
@dilipsonu if you have that fixed in a fork and want to send in a pull request, ttah owuld be great

**Comment by rshade** [comment] 2017-03-21 13:15
@RyanJarv what do you think about syminking those two on rhel?

**Comment by RyanJarv** [comment] 2017-03-22 04:18
That makes sense to me.

**Comment by RyanJarv** [comment] 2017-03-22 04:26
Actually had to think about that for a bit.. I think I like the idea of symlinking just makes the cookbook simpler. Only downsides I can think of are it's not what upstream does, and it's not consistent with the rest of the cookbook, but for the first one I don't think I care as much about following upstream when it makes the cookbook less complex and more reliable and for the second if we had anything else that is simple enough that could be symlinked it would probably make sense as well I think.

**Comment by RyanJarv** [comment] 2017-03-22 04:35
Some what unrelated but we may also want to take a look at what we are doing for varnishlog/varnishncsa, currently we manage the init script for varnishlog but not ncsa. Will probably open another ticket about that though.

**Closed** 2017-04-10 15:33 UTC
